[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
# Limit linting to package and tests; exclude notebooks and ad-hoc scripts
exclude = [
  "notebooks/**",
  "paper/**",
  "docs/**",
  "scripts/**",
  "advanced_monitor.py",
  "monitor_training.py",
  "monitor_mps.py",
  "notify_progress.py",
  "orchestrate.py",
  "collect_results.py"
]

[tool.ruff.lint]
select = ["E","F","I","B","C90"]
ignore = ["E203","E501","C901"]

