hyperopt:
  enabled: true
  n_trials: 100
  timeout: 7200  # 2 hours
  study_name: "suicide_detection_hyperopt"
  storage: "sqlite:///results/hyperopt.db"
  
  svm:
    parameters:
      C: 
        type: "log_uniform"
        low: 0.01
        high: 100.0
      ngram_range_max:
        type: "categorical"
        choices: [2, 3, 4]
      max_features:
        type: "categorical" 
        choices: [10000, 50000, 100000]
      class_weight:
        type: "categorical"
        choices: ["balanced", null]
        
  bilstm:
    parameters:
      hidden_size:
        type: "categorical"
        choices: [128, 256, 512]
      num_layers:
        type: "categorical"
        choices: [1, 2, 3]
      dropout:
        type: "uniform"
        low: 0.2
        high: 0.6
      learning_rate:
        type: "log_uniform"
        low: 1e-5
        high: 1e-2
      batch_size:
        type: "categorical"
        choices: [16, 32, 64]
      weight_decay:
        type: "log_uniform"
        low: 1e-6
        high: 1e-3
        
  bert:
    parameters:
      learning_rate:
        type: "log_uniform"
        low: 1e-6
        high: 5e-4
      per_device_train_batch_size:
        type: "categorical"
        choices: [8, 16, 32]
      num_train_epochs:
        type: "categorical"
        choices: [3, 4, 5]
      warmup_ratio:
        type: "uniform"
        low: 0.0
        high: 0.2
      weight_decay:
        type: "log_uniform"
        low: 1e-5
        high: 1e-1
      max_seq_length:
        type: "categorical"
        choices: [256, 512]

models:
  bert_variants:
    - "bert-base-uncased"
    - "roberta-base"
    - "distilbert-base-uncased"
    - "mental/mental-bert-base-uncased"
    - "microsoft/DialoGPT-medium"

evaluation:
  clinical_targets:
    min_accuracy: 0.95
    min_recall: 0.90
    min_precision: 0.85
    max_false_negative_rate: 0.10
  
  cost_matrix:
    # Clinical cost weighting (false negatives are 5x more costly)
    false_negative_cost: 5.0
    false_positive_cost: 1.0
    true_positive_reward: 0.0
    true_negative_reward: 0.0
    
  bootstrap:
    enabled: true
    n_resamples: 1000
    confidence_level: 0.95
