model: svm
svm:
  tfidf:
    analyzer: char_wb
    ngram_range: [3, 5]
    max_features: 200000
    sublinear_tf: true
    min_df: 2
  word_tfidf:
    analyzer: word
    ngram_range: [1, 3]
    max_features: 200000
    sublinear_tf: true
    min_df: 2
  clf:
    kernel: rbf
    C: 1.0
    gamma: scale
  grid_search:
    C: [0.5, 1.0, 2.0, 4.0]
    gamma: ["scale", "auto"]
    cv: 5
    n_jobs: -1
  class_balance:
    method: smote
    k_neighbors: 5
  max_seq_len: 256

