name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Lint
        run: |
          . .venv/bin/activate
          ruff check src tests
      - name: Format check
        run: |
          . .venv/bin/activate
          black --check src tests
      - name: Tests
        run: |
          . .venv/bin/activate
          pytest -q
      - name: Smoke preprocess
        run: |
          . .venv/bin/activate
          python scripts/preprocess.py --input data/sample/sample.csv --output data/processed/dataset.csv
      - name: Smoke train SVM
        env:
          DISABLE_GRID: "1"
        run: |
          . .venv/bin/activate
          python -m suicide_detection.training.train --model svm --data_path data/processed/dataset.csv --output_dir results/model_outputs/svm_ci
      - name: Generate report
        run: |
          . .venv/bin/activate
          python scripts/generate_report.py
      - name: Upload report and plots
        uses: actions/upload-artifact@v4
        with:
          name: results-artifacts
          path: |
            results/final_report.html
            results/**/*.png
            results/model_outputs/**/*.json

